### ISSUE TITLE
[Bug]: TypeError: (0 , react__WEBPACK_IMPORTED_MODULE_0__.createContext) is not a function

### ISSUE THREAD

**Issue by gHashTag** [100mslive/web-sdks#2662]
### What happened?

The app crashes during the build.

<img width="1512" alt="Снимок экрана 2024-03-06 в 13 59 26" src="https://github.com/100mslive/web-sdks/assets/6774813/63ef6d0c-0e5b-443c-aa85-66cc18dc7526">

### How can we reproduce the bug?

import { HMSPrebuilt } from '@100mslive/roomkit-react'

export default function Meets() {
  return <div style={{ height: '100vh' }}><HMSPrebuilt roomCode="********" /> </div>
}

` bun dev                                 
$ next dev
   ▲ Next.js 14.1.2
   - Local:        http://localhost:3000
   - Environments: .env

 ✓ Ready in 9.4s
 ○ Compiling /meets ...
 ✓ Compiled /meets in 23.5s (5944 modules)
[HMSIntersectionObserverWrapper] IntersectionObserver is not supported, fallback will be used instead
[HMSResizeObserverWrapper] Resize Observer is not supported
TypeError: (0 , react__WEBPACK_IMPORTED_MODULE_0__.createContext) is not a function
    at $c512c27ab02ef895$export$fd42f52fd3ae1109 (webpack-internal:///(rsc)/./node_modules/@100mslive/roomkit-react/node_modules/@radix-ui/react-label/node_modules/@radix-ui/react-context/dist/index.module.js:12:87)
    at eval (webpack-internal:///(rsc)/./node_modules/@100mslive/roomkit-react/node_modules/@radix-ui/react-label/dist/index.module.js:30:160)
    at (rsc)/./node_modules/@100mslive/roomkit-react/node_modules/@radix-ui/react-label/dist/index.module.js (/Users/playra/999-web3/.next/server/vendor-chunks/@100mslive.js:3490:1)
    at __webpack_require__ (/Users/playra/999-web3/.next/server/webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/./node_modules/@100mslive/roomkit-react/node_modules/@radix-ui/react-switch/dist/index.module.js:19:79)
    at (rsc)/./node_modules/@100mslive/roomkit-react/node_modules/@radix-ui/react-switch/dist/index.module.js (/Users/playra/999-web3/.next/server/vendor-chunks/@100mslive.js:4230:1)
    at __webpack_require__ (/Users/playra/999-web3/.next/server/webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/./node_modules/@100mslive/roomkit-react/dist/chunk-LCECN6XD.js:97:80)
    at (rsc)/./node_modules/@100mslive/roomkit-react/dist/chunk-LCECN6XD.js (/Users/playra/999-web3/.next/server/vendor-chunks/@100mslive.js:3120:1)
    at __webpack_require__ (/Users/playra/999-web3/.next/server/webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/./app/meets/page.tsx:7:82)
    at (rsc)/./app/meets/page.tsx (/Users/playra/999-web3/.next/server/app/meets/page.js:552:1)
    at Function.__webpack_require__ (/Users/playra/999-web3/.next/server/webpack-runtime.js:33:43)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at listOnTimeout (node:internal/timers:540:9)
    at process.processTimers (node:internal/timers:514:7)
    at async eB (/Users/playra/999-web3/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:402523)
    at async tt (/Users/playra/999-web3/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:406237)
    at async tr (/Users/playra/999-web3/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:406787)
    at async tr (/Users/playra/999-web3/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:406918)
    at async tr (/Users/playra/999-web3/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:406918)
    at async tl (/Users/playra/999-web3/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:36:2057)
    at async /Users/playra/999-web3/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:36:2596 {
  digest: '1837371966'
}
TypeError: (0 , react__WEBPACK_IMPORTED_MODULE_0__.createContext) is not a function
    at $c512c27ab02ef895$export$fd42f52fd3ae1109 (webpack-internal:///(rsc)/./node_modules/@100mslive/roomkit-react/node_modules/@radix-ui/react-label/node_modules/@radix-ui/react-context/dist/index.module.js:12:87)
    at eval (webpack-internal:///(rsc)/./node_modules/@100mslive/roomkit-react/node_modules/@radix-ui/react-label/dist/index.module.js:30:160)
    at (rsc)/./node_modules/@100mslive/roomkit-react/node_modules/@radix-ui/react-label/dist/index.module.js (/Users/playra/999-web3/.next/server/vendor-chunks/@100mslive.js:3490:1)
    at __webpack_require__ (/Users/playra/999-web3/.next/server/webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/./node_modules/@100mslive/roomkit-react/node_modules/@radix-ui/react-switch/dist/index.module.js:19:79)
    at (rsc)/./node_modules/@100mslive/roomkit-react/node_modules/@radix-ui/react-switch/dist/index.module.js (/Users/playra/999-web3/.next/server/vendor-chunks/@100mslive.js:4230:1)
    at __webpack_require__ (/Users/playra/999-web3/.next/server/webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/./node_modules/@100mslive/roomkit-react/dist/chunk-LCECN6XD.js:97:80)
    at (rsc)/./node_modules/@100mslive/roomkit-react/dist/chunk-LCECN6XD.js (/Users/playra/999-web3/.next/server/vendor-chunks/@100mslive.js:3120:1)
    at __webpack_require__ (/Users/playra/999-web3/.next/server/webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/./app/meets/page.tsx:7:82)
    at (rsc)/./app/meets/page.tsx (/Users/playra/999-web3/.next/server/app/meets/page.js:552:1)
    at Function.__webpack_require__ (/Users/playra/999-web3/.next/server/webpack-runtime.js:33:43)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at listOnTimeout (node:internal/timers:540:9)
    at process.processTimers (node:internal/timers:514:7)
    at async eB (/Users/playra/999-web3/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:402523)
    at async tt (/Users/playra/999-web3/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:406237)
    at async tr (/Users/playra/999-web3/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:406787)
    at async tr (/Users/playra/999-web3/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:406918)
    at async tr (/Users/playra/999-web3/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:406918)
    at async tl (/Users/playra/999-web3/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:36:2057)
    at async /Users/playra/999-web3/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:36:2596 {
  digest: '1837371966'
}
 ⨯ node_modules/@100mslive/roomkit-react/node_modules/@radix-ui/react-label/node_modules/@radix-ui/react-context/dist/index.module.js (5:54) @ $c512c27ab02ef895$export$fd42f52fd3ae1109
 ⨯ TypeError: (0 , react__WEBPACK_IMPORTED_MODULE_0__.createContext) is not a function
    at __webpack_require__ (/Users/playra/999-web3/.next/server/webpack-runtime.js:33:43)
    at __webpack_require__ (/Users/playra/999-web3/.next/server/webpack-runtime.js:33:43)
    at __webpack_require__ (/Users/playra/999-web3/.next/server/webpack-runtime.js:33:43)
    at eval (./app/meets/page.tsx:7:82)
    at (rsc)/./app/meets/page.tsx (/Users/playra/999-web3/.next/server/app/meets/page.js:552:1)
    at Function.__webpack_require__ (/Users/playra/999-web3/.next/server/webpack-runtime.js:33:43)
    at async Promise.all (index 0)
    at async Promise.all (index 0)
null
 ⨯ node_modules/@100mslive/roomkit-react/node_modules/@radix-ui/react-label/node_modules/@radix-ui/react-context/dist/index.module.js (5:54) @ $c512c27ab02ef895$export$fd42f52fd3ae1109
 ⨯ TypeError: (0 , react__WEBPACK_IMPORTED_MODULE_0__.createContext) is not a function
    at __webpack_require__ (/Users/playra/999-web3/.next/server/webpack-runtime.js:33:43)
    at __webpack_require__ (/Users/playra/999-web3/.next/server/webpack-runtime.js:33:43)
    at __webpack_require__ (/Users/playra/999-web3/.next/server/webpack-runtime.js:33:43)
    at eval (./app/meets/page.tsx:7:82)
    at (rsc)/./app/meets/page.tsx (/Users/playra/999-web3/.next/server/app/meets/page.js:552:1)
    at Function.__webpack_require__ (/Users/playra/999-web3/.next/server/webpack-runtime.js:33:43)
    at async Promise.all (index 0)
    at async Promise.all (index 0)
null
 ⨯ node_modules/@100mslive/roomkit-react/node_modules/@radix-ui/react-label/node_modules/@radix-ui/react-context/dist/index.module.js (5:54) @ $c512c27ab02ef895$export$fd42f52fd3ae1109
 ⨯ TypeError: (0 , react__WEBPACK_IMPORTED_MODULE_0__.createContext) is not a function
    at __webpack_require__ (/Users/playra/999-web3/.next/server/webpack-runtime.js:33:43)
    at __webpack_require__ (/Users/playra/999-web3/.next/server/webpack-runtime.js:33:43)
    at __webpack_require__ (/Users/playra/999-web3/.next/server/webpack-runtime.js:33:43)
    at eval (./app/meets/page.tsx:7:82)
    at (rsc)/./app/meets/page.tsx (/Users/playra/999-web3/.next/server/app/meets/page.js:552:1)
    at Function.__webpack_require__ (/Users/playra/999-web3/.next/server/webpack-runtime.js:33:43)
    at async Promise.all (index 0)
    at async Promise.all (index 0)
digest: "1486812798"
null
 ⨯ node_modules/@100mslive/roomkit-react/node_modules/@radix-ui/react-label/node_modules/@radix-ui/react-context/dist/index.module.js (5:54) @ $c512c27ab02ef895$export$fd42f52fd3ae1109
 ⨯ TypeError: (0 , react__WEBPACK_IMPORTED_MODULE_0__.createContext) is not a function
    at __webpack_require__ (/Users/playra/999-web3/.next/server/webpack-runtime.js:33:43)
    at __webpack_require__ (/Users/playra/999-web3/.next/server/webpack-runtime.js:33:43)
    at __webpack_require__ (/Users/playra/999-web3/.next/server/webpack-runtime.js:33:43)
    at eval (./app/meets/page.tsx:7:82)
    at (rsc)/./app/meets/page.tsx (/Users/playra/999-web3/.next/server/app/meets/page.js:552:1)
    at Function.__webpack_require__ (/Users/playra/999-web3/.next/server/webpack-runtime.js:33:43)
    at async Promise.all (index 0)
    at async Promise.all (index 0)
digest: "919926608"
null
 ⨯ node_modules/@100mslive/roomkit-react/node_modules/@radix-ui/react-label/node_modules/@radix-ui/react-context/dist/index.module.js (5:54) @ $c512c27ab02ef895$export$fd42f52fd3ae1109
 ⨯ TypeError: (0 , react__WEBPACK_IMPORTED_MODULE_0__.createContext) is not a function
    at __webpack_require__ (/Users/playra/999-web3/.next/server/webpack-runtime.js:33:43)
    at __webpack_require__ (/Users/playra/999-web3/.next/server/webpack-runtime.js:33:43)
    at __webpack_require__ (/Users/playra/999-web3/.next/server/webpack-runtime.js:33:43)
    at eval (./app/meets/page.tsx:7:82)
    at (rsc)/./app/meets/page.tsx (/Users/playra/999-web3/.next/server/app/meets/page.js:552:1)
    at Function.__webpack_require__ (/Users/playra/999-web3/.next/server/webpack-runtime.js:33:43)
null
 ⨯ node_modules/@100mslive/roomkit-react/node_modules/@radix-ui/react-label/node_modules/@radix-ui/react-context/dist/index.module.js (5:54) @ $c512c27ab02ef895$export$fd42f52fd3ae1109
 ⨯ TypeError: (0 , react__WEBPACK_IMPORTED_MODULE_0__.createContext) is not a function
    at __webpack_require__ (/Users/playra/999-web3/.next/server/webpack-runtime.js:33:43)
    at __webpack_require__ (/Users/playra/999-web3/.next/server/webpack-runtime.js:33:43)
    at __webpack_require__ (/Users/playra/999-web3/.next/server/webpack-runtime.js:33:43)
    at eval (./app/meets/page.tsx:7:82)
    at (rsc)/./app/meets/page.tsx (/Users/playra/999-web3/.next/server/app/meets/page.js:552:1)
    at Function.__webpack_require__ (/Users/playra/999-web3/.next/server/webpack-runtime.js:33:43)
null
 ⨯ node_modules/@100mslive/roomkit-react/node_modules/@radix-ui/react-label/node_modules/@radix-ui/react-context/dist/index.module.js (5:54) @ $c512c27ab02ef895$export$fd42f52fd3ae1109
 ⨯ TypeError: (0 , react__WEBPACK_IMPORTED_MODULE_0__.createContext) is not a function
    at $c512c27ab02ef895$export$fd42f52fd3ae1109 (webpack-internal:///(rsc)/./node_modules/@100mslive/roomkit-react/node_modules/@radix-ui/react-label/node_modules/@radix-ui/react-context/dist/index.module.js:12:87)
    at eval (webpack-internal:///(rsc)/./node_modules/@100mslive/roomkit-react/node_modules/@radix-ui/react-label/dist/index.module.js:30:160)
    at (rsc)/./node_modules/@100mslive/roomkit-react/node_modules/@radix-ui/react-label/dist/index.module.js (/Users/playra/999-web3/.next/server/vendor-chunks/@100mslive.js:3490:1)
    at __webpack_require__ (/Users/playra/999-web3/.next/server/webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/./node_modules/@100mslive/roomkit-react/node_modules/@radix-ui/react-switch/dist/index.module.js:19:79)
    at (rsc)/./node_modules/@100mslive/roomkit-react/node_modules/@radix-ui/react-switch/dist/index.module.js (/Users/playra/999-web3/.next/server/vendor-chunks/@100mslive.js:4230:1)
    at __webpack_require__ (/Users/playra/999-web3/.next/server/webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/./node_modules/@100mslive/roomkit-react/dist/chunk-LCECN6XD.js:97:80)
    at (rsc)/./node_modules/@100mslive/roomkit-react/dist/chunk-LCECN6XD.js (/Users/playra/999-web3/.next/server/vendor-chunks/@100mslive.js:3120:1)
    at __webpack_require__ (/Users/playra/999-web3/.next/server/webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/./app/meets/page.tsx:7:82)
    at (rsc)/./app/meets/page.tsx (/Users/playra/999-web3/.next/server/app/meets/page.js:552:1)
    at Function.__webpack_require__ (/Users/playra/999-web3/.next/server/webpack-runtime.js:33:43)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at listOnTimeout (node:internal/timers:540:9)
    at process.processTimers (node:internal/timers:514:7)
    at async eB (/Users/playra/999-web3/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:402523)
    at async tt (/Users/playra/999-web3/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:406237)
    at async tr (/Users/playra/999-web3/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:406787)
    at async tr (/Users/playra/999-web3/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:406918)
    at async tr (/Users/playra/999-web3/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:406918)
    at async tl (/Users/playra/999-web3/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:36:2057)
    at async /Users/playra/999-web3/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:36:2596 {
  digest: '1837371966',
  page: '/meets'
}
null
 ⨯ node_modules/@100mslive/roomkit-react/node_modules/@radix-ui/react-label/node_modules/@radix-ui/react-context/dist/index.module.js (5:54) @ $c512c27ab02ef895$export$fd42f52fd3ae1109
 ⨯ TypeError: (0 , react__WEBPACK_IMPORTED_MODULE_0__.createContext) is not a function
    at $c512c27ab02ef895$export$fd42f52fd3ae1109 (webpack-internal:///(rsc)/./node_modules/@100mslive/roomkit-react/node_modules/@radix-ui/react-label/node_modules/@radix-ui/react-context/dist/index.module.js:12:87)
    at eval (webpack-internal:///(rsc)/./node_modules/@100mslive/roomkit-react/node_modules/@radix-ui/react-label/dist/index.module.js:30:160)
    at (rsc)/./node_modules/@100mslive/roomkit-react/node_modules/@radix-ui/react-label/dist/index.module.js (/Users/playra/999-web3/.next/server/vendor-chunks/@100mslive.js:3490:1)
    at __webpack_require__ (/Users/playra/999-web3/.next/server/webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/./node_modules/@100mslive/roomkit-react/node_modules/@radix-ui/react-switch/dist/index.module.js:19:79)
    at (rsc)/./node_modules/@100mslive/roomkit-react/node_modules/@radix-ui/react-switch/dist/index.module.js (/Users/playra/999-web3/.next/server/vendor-chunks/@100mslive.js:4230:1)
    at __webpack_require__ (/Users/playra/999-web3/.next/server/webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/./node_modules/@100mslive/roomkit-react/dist/chunk-LCECN6XD.js:97:80)
    at (rsc)/./node_modules/@100mslive/roomkit-react/dist/chunk-LCECN6XD.js (/Users/playra/999-web3/.next/server/vendor-chunks/@100mslive.js:3120:1)
    at __webpack_require__ (/Users/playra/999-web3/.next/server/webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/./app/meets/page.tsx:7:82)
    at (rsc)/./app/meets/page.tsx (/Users/playra/999-web3/.next/server/app/meets/page.js:552:1)
    at Function.__webpack_require__ (/Users/playra/999-web3/.next/server/webpack-runtime.js:33:43)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at listOnTimeout (node:internal/timers:540:9)
    at process.processTimers (node:internal/timers:514:7)
    at async eB (/Users/playra/999-web3/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:402523)
    at async tt (/Users/playra/999-web3/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:406237)
    at async tr (/Users/playra/999-web3/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:406787)
    at async tr (/Users/playra/999-web3/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:406918)
    at async tr (/Users/playra/999-web3/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:406918)
    at async tl (/Users/playra/999-web3/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:36:2057)
    at async /Users/playra/999-web3/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:36:2596 {
  digest: '1837371966',
  page: '/meets'
}
null
 ○ Compiling /_error ...
`

### What browsers are you seeing the problem on?

Chrome

**Comment by raviteja83** [comment]
@gHashTag Try using 'use client' on the top of the file. The APi's are not supported on server side .

**Comment by KaustubhKumar05** [comment]
Hey @gHashTag, adding `use client` at the top of the file should fix this as @raviteja83 mentioned. I tried a sample app with bun and Next, got the same error on removing `use client`.  You can check out our integration doc [here].(https://www.100ms.live/docs/javascript/v2/quickstart/prebuilt-quickstart#add-prebuilt-component)
