### ISSUE TITLE
[Bug]: [vite:resolve] Missing "./dist-esm/lib/core/capture.mjs.js" export in "@tldraw/state" package

### ISSUE THREAD

**Issue by sicoware** [100mslive/web-sdks#2933]
### What happened?

`npm run build ` fails with vite

To reproduce:
`npm init quasar`
`npm install @100mslive/roomkit-web`

add sample code as from https://github.com/100mslive/web-sdks/tree/main/packages/roomkit-web in src/pages/IndexPage.vue

`<template>
  <q-page class="flex flex-center">
    <img
      alt="Quasar logo"
      src="~assets/quasar-logo-vertical.svg"
      style="width: 200px; height: 200px"
    >
    <hms-prebuilt room-code="<room-code-goes-here>"></hms-prebuilt>
  </q-page>
</template>

<script>
import { defineComponent } from 'vue'
import '@100mslive/roomkit-web';

export default defineComponent({
  name: 'IndexPage'
})
</script>`

Running: `npm run dev` all works fine but using npm run build I get:
```
 Build mode............. spa
 Pkg quasar............. v2.16.4
 Pkg @quasar/app-vite... v1.9.3
 Pkg vite............... v2.9.18
 Debugging.............. no
 Publishing............. no

 App •  WAIT  • Compiling of SPA UI with Vite in progress...
Module level directives cause errors when bundled, 'use client' was ignored.
[vite:resolve] Missing "./dist-esm/lib/core/capture.mjs.js" export in "@tldraw/state" package
Error: Missing "./dist-esm/lib/core/capture.mjs.js" export in "@tldraw/state" package
    at bail (/Users/sico/Documents/test-100ms/quasar-project/node_modules/vite/dist/node/chunks/dep-0a035c79.js:38597:8)
    at resolve (/Users/sico/Documents/test-100ms/quasar-project/node_modules/vite/dist/node/chunks/dep-0a035c79.js:38674:10)
    at resolveExports (/Users/sico/Documents/test-100ms/quasar-project/node_modules/vite/dist/node/chunks/dep-0a035c79.js:40982:12)
    at resolveDeepImport (/Users/sico/Documents/test-100ms/quasar-project/node_modules/vite/dist/node/chunks/dep-0a035c79.js:41000:31)
    at tryNodeResolve (/Users/sico/Documents/test-100ms/quasar-project/node_modules/vite/dist/node/chunks/dep-0a035c79.js:40773:20)
    at Object.resolveId (/Users/sico/Documents/test-100ms/quasar-project/node_modules/vite/dist/node/chunks/dep-0a035c79.js:40528:32)
    at /Users/sico/Documents/test-100ms/quasar-project/node_modules/rollup/dist/shared/rollup.js:22826:37 {
  code: 'PLUGIN_ERROR',
  plugin: 'vite:resolve',
  hook: 'resolveId',
```

**Comment by raviteja83** [comment]
@sicoware please upgrade to the latest version of the package and check. if the issue still exists, please reopen.
